version: '3.8'

services:
  grobid:
    image: grobid/grobid:latest
    restart: unless-stopped
    ports:
      - "9080:8070"  # Map port 9080 on the host to port 8070 on the container
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    ulimits:
      core: 0