image: docker:latest

stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: grobid/grobid

default:
  before_script:
    - rm -f $(pwd)/docker.sock
    - echo ${REMOTE_DOCKER_HOST}
    - ssh -nNT -L $(pwd)/docker.sock:/var/run/docker.sock ${REMOTE_DOCKER_HOST} &

.step-build:
  stage: build
  tags:
    - linux
  script:
    - DOCKER_HOST=unix://$(pwd)/docker.sock docker compose build
    - kill %1

.step-deploy:
  stage: deploy
  tags:
    - linux
  script:
    - DOCKER_HOST=unix://$(pwd)/docker.sock docker compose up -d
    - kill %1

step-build-dev:
  extends: .step-build
  environment:
    name: development
  only:
    - develop

step-build-prod:
  extends: .step-build
  environment:
    name: production
  only:
    - master

step-deploy-dev:
  extends: .step-deploy
  environment:
    name: development
    url: http://${REMOTE_DOCKER_HOST}:8070
  only:
    - develop

step-deploy-prod:
  extends: .step-deploy
  environment:
    name: production
    url: http://${REMOTE_DOCKER_HOST}:8070
  only:
    - master