# Each change gets pushed on the server by this gitlab functionality through CI/CD (Continuous Integration and Continuous Deployment (or Delivery))
image: docker:latest

stages:
  - deploy

variables:
  DOCKER_COMPOSE_FILE: docker-compose.yml

default:
  before_script:
    - rm -f $(pwd)/docker.sock
    - echo ${REMOTE_DOCKER_HOST}
    - ssh -nNT -L $(pwd)/docker.sock:/var/run/docker.sock ${REMOTE_DOCKER_HOST} &

.step-deploy:
  stage: deploy
  tags:
    - linux
  script:
    - DOCKER_HOST=unix://$(pwd)/docker.sock docker compose up -d --force-recreate
    - kill %1

step-deploy-dev:
  extends: .step-deploy
  environment:
    name: development
    url: http://${REMOTE_DOCKER_HOST}:8070
  only:
    - develop

# step-deploy-prod:
#   extends: .step-deploy
#   environment:
#     name: production
#     url: http://${REMOTE_DOCKER_HOST}:8070
#   only:
#     - master