services:
  grobid:
    image: grobid/grobid:0.8.0
    container_name: my-grobid-container
    restart: unless-stopped
    ports:
      - "8070:8070"  # Ports Host:Container
    ulimits:
      core: 0